language: cpp

compiler:
    - clang
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
        packages:
            - cmake
            - libgtest-dev
            - g++-5
            - gcc-5
            - clang-3.8

before_script:
    - if [ "$CXX" = "g++" ];     then export CXX="g++-5"       CC="gcc-5";     fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
    - cd ./test/build
    - mkdir ./cmake_build
    - cd ./cmake_build
    - mkdir ./gtest
    - cd ./gtest
    - cmake /usr/src/gtest
    - make
    - mv libg* ../
    - cd ../
    - cmake ../
    - make

script: ./cue_tests
