language: cpp

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
        packages:
            - cmake
            - g++-5
            - gcc-5
            - git

before_script:
    - export CXX="g++-5" CC="gcc-5"
    - cd ./test/build
    - mkdir ./cmake_build
    - cd ./cmake_build
    - git clone https://github.com/google/googletest.git
    - cd ./googletest/googletest
    - export GTEST_ROOT=`pwd`
    - mkdir build
    - cd build
    - cmake ../
    - make
    - cd ../../../
    - cmake ../ -DGTEST_INCLUDE=$GTEST_ROOT/include -DGTEST_LIB=$GTEST_ROOT/build
    - make

script: ./cue_tests

