language: cpp

compiler:
    - clang
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
        packages:
            - cmake
            - libgtest-dev

before_script:
    - cd ./test/build
    - mkdir ./cmake_build
    - cd ./cmake_build
    - mkdir ./gtest
    - cd ./gtest
    - cmake /usr/src/gtest
    - make
    - mv libg* ../
    - cd ../
    - cmake ../
    - make

script: ./cue_tests
